import { useState, type FormEvent } from 'react';
import { Navigate } from 'react-router-dom';
import { ChevronLeft, LockKeyhole, Phone, Pill } from 'lucide-react';
import { useAuth } from '../context/auth-context';
import { Button } from '../components/ui/button';
import { Input, Label } from '../components/ui/core';
import { useAsync } from '../hooks/use-async';
import { apiGet } from '../lib/api';

export function LoginPage() {
  const { user, login } = useAuth(); const [phone, setPhone] = useState('+201000000001'); const [password, setPassword] = useState('Admin@123'); const [error, setError] = useState(''); const [loading, setLoading] = useState(false);
  const publicSettings = useAsync(() => apiGet<{ pharmacyName: string }>('/auth/public-settings'), []);
  const pharmacyName = publicSettings.data?.pharmacyName || 'صيدلية ديمو';
  if (user) return <Navigate to="/dashboard" replace/>;
  const submit = async (event: FormEvent) => { event.preventDefault(); setLoading(true); setError(''); try { await login(phone, password); } catch (err) { setError(err instanceof Error ? err.message : 'تعذر تسجيل الدخول.'); } finally { setLoading(false); } };
  return <div className="grid min-h-screen bg-white lg:grid-cols-[1.05fr_.95fr]">
    <section className="relative hidden overflow-hidden bg-primary p-12 text-primary-foreground lg:flex lg:flex-col"><div className="absolute -left-36 -top-36 size-96 rounded-full border border-white/10"/><div className="absolute -left-20 -top-20 size-72 rounded-full border border-white/10"/><div className="flex items-center gap-3"><div className="grid size-10 place-items-center rounded-md bg-white/15"><Pill className="size-5"/></div><span className="font-bold">{pharmacyName}</span></div><div className="my-auto max-w-xl"><p className="mb-4 text-sm font-semibold text-blue-100">إدارة متكاملة للصيدلية</p><h1 className="text-5xl font-bold leading-[1.2] tracking-tight">طريقة أسرع وأكثر أمانًا لإدارة كل وردية.</h1><p className="mt-6 max-w-lg text-lg leading-8 text-blue-50/80">نفّذ المبيعات بثقة، وتتبع كل دفعة، واستلم المخزون، وراقب مخاطر انتهاء الصلاحية من مكان واحد موثوق.</p><div className="mt-10 grid grid-cols-3 gap-3 text-sm"><div className="border-r border-blue-100/30 pr-4"><strong className="block text-2xl">FEFO</strong><span className="text-blue-50/70">تخصيص الدفعات</span></div><div className="border-r border-blue-100/30 pr-4"><strong className="block text-2xl">مباشر</strong><span className="text-blue-50/70">دقة المخزون</span></div><div className="border-r border-blue-100/30 pr-4"><strong className="block text-2xl">صلاحيات</strong><span className="text-blue-50/70">حسب الدور</span></div></div></div><p className="text-xs text-blue-50/60">مصمم لفريق صيدلية واحد ومترابط.</p></section>
    <section className="flex items-center justify-center px-5 py-12"><div className="w-full max-w-md"><div className="mb-10 flex items-center gap-3 lg:hidden"><div className="grid size-10 place-items-center rounded-md bg-primary text-primary-foreground"><Pill className="size-5"/></div><span className="font-bold">{pharmacyName}</span></div><p className="text-sm font-semibold text-primary">مرحبًا بعودتك</p><h2 className="mt-2 text-3xl font-bold tracking-tight text-foreground">سجّل الدخول إلى ورديتك</h2><p className="mt-2 text-sm text-muted-foreground">استخدم رقم هاتف الموظف وكلمة المرور.</p><form className="mt-8 space-y-5" onSubmit={submit}><div><Label>رقم الهاتف</Label><div className="relative"><Phone className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input className="pl-10" autoComplete="tel" value={phone} onChange={(e) => setPhone(e.target.value)} required/></div></div><div><Label>كلمة المرور</Label><div className="relative"><LockKeyhole className="absolute left-3 top-3 size-4 text-muted-foreground"/><Input className="pl-10" type="password" autoComplete="current-password" value={password} onChange={(e) => setPassword(e.target.value)} required/></div></div>{error && <div role="alert" className="rounded-md bg-red-50 px-3 py-2 text-sm text-red-700">{error}</div>}<Button size="lg" className="w-full" disabled={loading}>{loading ? 'جارٍ تسجيل الدخول…' : <>تسجيل الدخول <ChevronLeft className="size-4"/></>}</Button></form><div className="mt-8 rounded-md border border-border bg-muted p-4 text-xs leading-5 text-muted-foreground"><strong className="text-foreground">بيانات الدخول التجريبية</strong><br/><bdi>Admin: +201000000001 · Admin@123</bdi></div></div></section>
  </div>;
}
