import { forwardRef, type HTMLAttributes, type InputHTMLAttributes, type ReactNode, type SelectHTMLAttributes, type TdHTMLAttributes, type TextareaHTMLAttributes } from 'react';
import { AlertCircle, LoaderCircle, SearchX } from 'lucide-react';
import { cn } from '../../lib/utils';
import { Button } from './button';

export function Card({ className, ...props }: HTMLAttributes<HTMLDivElement>) { return <div className={cn('rounded-md border border-border bg-card text-card-foreground shadow-[0_1px_2px_rgba(15,23,42,.04)]', className)} {...props} />; }
export const Input = forwardRef<HTMLInputElement, InputHTMLAttributes<HTMLInputElement>>(function Input(props, ref) { return <input ref={ref} {...props} className={cn('h-10 w-full rounded-md border border-input bg-background px-3 text-sm text-foreground outline-none placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-ring/20 disabled:bg-muted disabled:text-muted-foreground', props.className)} />; });
export function Select(props: SelectHTMLAttributes<HTMLSelectElement>) { return <select {...props} className={cn('h-10 w-full rounded-md border border-input bg-background px-3 text-sm text-foreground outline-none focus:border-primary focus:ring-2 focus:ring-ring/20', props.className)} />; }
export function Textarea(props: TextareaHTMLAttributes<HTMLTextAreaElement>) { return <textarea {...props} className={cn('min-h-24 w-full rounded-md border border-input bg-background px-3 py-2 text-sm text-foreground outline-none placeholder:text-muted-foreground focus:border-primary focus:ring-2 focus:ring-ring/20', props.className)} />; }
export function Label({ children, className }: { children: ReactNode; className?: string }) { return <label className={cn('mb-1.5 block text-sm font-medium text-foreground', className)}>{children}</label>; }
export function Badge({ children, tone = 'slate' }: { children: ReactNode; tone?: 'slate'|'green'|'amber'|'red'|'blue'|'purple' }) { const colors = { slate: 'bg-slate-100 text-slate-700', green: 'bg-emerald-50 text-emerald-700 ring-emerald-600/20', amber: 'bg-amber-50 text-amber-700 ring-amber-600/20', red: 'bg-red-50 text-red-700 ring-red-600/20', blue: 'bg-blue-50 text-blue-700 ring-blue-600/20', purple: 'bg-purple-50 text-purple-700 ring-purple-600/20' }; return <span className={cn('inline-flex items-center rounded-full px-2 py-1 text-[11px] font-semibold uppercase tracking-wide ring-1 ring-inset', colors[tone])}>{children}</span>; }
export function PageHeader({ title, description, action }: { title: string; description?: string; action?: ReactNode }) { return <div className="mb-6 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-bold tracking-tight text-foreground">{title}</h1>{description && <p className="mt-1 text-sm text-muted-foreground">{description}</p>}</div>{action}</div>; }
export function Field({ label, children }: { label: string; children: ReactNode }) { return <div><Label>{label}</Label>{children}</div>; }
export function StateView({ loading, error, empty, onRetry, children }: { loading?: boolean; error?: string | null; empty?: boolean; onRetry?: () => void; children: ReactNode }) {
  if (loading) return <div className="flex min-h-48 items-center justify-center gap-2 text-sm text-slate-500"><LoaderCircle className="size-5 animate-spin"/> جارٍ التحميل…</div>;
  if (error) return <div className="flex min-h-48 flex-col items-center justify-center text-center"><AlertCircle className="mb-3 size-8 text-red-500"/><p className="font-semibold text-slate-800">تعذر تحميل هذه الصفحة</p><p className="mt-1 max-w-md text-sm text-slate-500">{error}</p>{onRetry && <Button className="mt-4" variant="outline" onClick={onRetry}>إعادة المحاولة</Button>}</div>;
  if (empty) return <div className="flex min-h-48 flex-col items-center justify-center text-center"><SearchX className="mb-3 size-8 text-slate-400"/><p className="font-semibold text-slate-800">لا توجد بيانات بعد</p><p className="mt-1 text-sm text-slate-500">جرّب تغيير عوامل التصفية أو إضافة سجل جديد.</p></div>;
  return <>{children}</>;
}
export function Table({ children }: { children: ReactNode }) { return <div className="overflow-x-auto"><table className="w-full min-w-[720px] border-collapse text-right text-sm">{children}</table></div>; }
export function Th({ children }: { children?: ReactNode }) { return <th className="border-b border-border bg-muted px-4 py-3 text-xs font-semibold uppercase tracking-wide text-muted-foreground">{children}</th>; }
export function Td({ children, className, ...props }: TdHTMLAttributes<HTMLTableCellElement>) { return <td className={cn('border-b border-border px-4 py-3 text-secondary-foreground', className)} {...props}>{children}</td>; }
